@startuml
' PlantUML Lexical Dependency Graph
skinparam componentStyle uml2
component [shop] as shop <<NN>>
component [condition] as condition <<NNS>>
shop --> condition : compound
component [shop] as shop <<NN>>
component [pet] as pet <<NNP>>
shop --> pet : compound
component [have] as have <<VBZ>>
component [shop] as shop <<NN>>
have --> shop : nsubj
component [inventory] as inventory <<NN>>
component [date] as date <<NN>>
inventory --> date : compound
component [have] as have <<VBZ>>
component [inventory] as inventory <<NN>>
have --> inventory : obj
component [inventory] as inventory <<NN>>
component [product] as product <<NNS>>
inventory --> product : nmod:of
component [have] as have <<VBZ>>
component [category] as category <<NNS>>
have --> category : obl:across
component [category] as category <<NNS>>
component [food] as food <<NN>>
category --> food : appos
component [food] as food <<NN>>
component [toy] as toy <<NNS>>
food --> toy : conj
component [food] as food <<NN>>
component [accessory] as accessory <<NNS>>
food --> accessory : conj
component [food] as food <<NN>>
component [groom] as groom <<VBG>>
food --> groom : acl
component [groom] as groom <<VBG>>
component [supply] as supply <<NNS>>
groom --> supply : obj
component [receive] as receive <<VBZ>>
component [customer] as customer <<NN>>
receive --> customer : nsubj
component [receive] as receive <<VBZ>>
component [receipt] as receipt <<NN>>
receive --> receipt : iobj
component [receipt] as receipt <<NN>>
component [print] as print <<VBN>>
receipt --> print : dep
component [name] as name <<VB>>
component [sell] as sell <<VBG>>
name --> sell : dep
component [owner] as owner <<NNP>>
component [pet] as pet <<NNP>>
owner --> pet : compound
component [customer] as customer <<NN>>
component [owner] as owner <<NNP>>
customer --> owner : appos
component [description] as description <<NN>>
component [description] as description <<NN>>
description --> description : compound
component [shop] as shop <<NN>>
component [pet] as pet <<NN>>
shop --> pet : compound
component [offer] as offer <<VBZ>>
component [shop] as shop <<NN>>
offer --> shop : nsubj
component [description] as description <<NN>>
component [offer] as offer <<VBZ>>
description --> offer : dep
component [offer] as offer <<VBZ>>
component [range] as range <<NN>>
offer --> range : obj
component [product] as product <<NNS>>
component [pet] as pet <<NN>>
product --> pet : compound
component [range] as range <<NN>>
component [product] as product <<NNS>>
range --> product : nmod:of
component [product] as product <<NNS>>
component [food] as food <<NN>>
product --> food : nmod:including
component [product] as product <<NNS>>
component [toy] as toy <<NNS>>
product --> toy : nmod:including
component [food] as food <<NN>>
component [toy] as toy <<NNS>>
food --> toy : conj:and
component [product] as product <<NNS>>
component [accessory] as accessory <<NNS>>
product --> accessory : nmod:including
component [food] as food <<NN>>
component [accessory] as accessory <<NNS>>
food --> accessory : conj:and
component [supply] as supply <<NNS>>
component [groom] as groom <<VBG>>
supply --> groom : amod
component [product] as product <<NNS>>
component [supply] as supply <<NNS>>
product --> supply : nmod:including
component [food] as food <<NN>>
component [supply] as supply <<NNS>>
food --> supply : conj:and
component [product] as product <<NNS>>
component [allow] as allow <<VBG>>
product --> allow : acl
component [allow] as allow <<VBG>>
component [customer] as customer <<NNS>>
allow --> customer : obj
component [browse] as browse <<VB>>
component [customer] as customer <<NNS>>
browse --> customer : nsubj:xsubj
component [allow] as allow <<VBG>>
component [browse] as browse <<VB>>
allow --> browse : xcomp
component [allow] as allow <<VBG>>
component [purchase] as purchase <<VB>>
allow --> purchase : xcomp
component [browse] as browse <<VB>>
component [purchase] as purchase <<VB>>
browse --> purchase : conj:and
component [browse] as browse <<VB>>
component [item] as item <<NNS>>
browse --> item : obj
component [item] as item <<NNS>>
component [pet] as pet <<NNS>>
item --> pet : nmod:for
component [item] as item <<NNS>>
component [store] as store <<NN>>
item --> store : nmod:in
component [item] as item <<NNS>>
component [online] as online <<NN>>
item --> online : nmod:in
component [store] as store <<NN>>
component [online] as online <<NN>>
store --> online : conj:or
component [provide] as provide <<VBZ>>
component [customer] as customer <<NN>>
provide --> customer : nsubj
component [catalog] as catalog <<NN>>
component [product] as product <<NN>>
catalog --> product : compound
component [load] as load <<VB>>
component [catalog] as catalog <<NN>>
load --> catalog : nsubj
component [load] as load <<VB>>
component [second] as second <<NNS>>
load --> second : obl:within
component [action] as action <<NNP>>
component [display] as display <<VBZ>>
action --> display : dep
component [action] as action <<NNP>>
component [prompt] as prompt <<VBZ>>
action --> prompt : dep
component [display] as display <<VBZ>>
component [prompt] as prompt <<VBZ>>
display --> prompt : conj:and
component [prompt] as prompt <<VBZ>>
component [customer] as customer <<NN>>
prompt --> customer : obj
component [provide] as provide <<VB>>
component [customer] as customer <<NN>>
provide --> customer : nsubj:xsubj
component [prompt] as prompt <<VBZ>>
component [provide] as provide <<VB>>
prompt --> provide : xcomp
component [method] as method <<NN>>
component [payment] as payment <<NN>>
method --> payment : compound
component [provide] as provide <<VB>>
component [method] as method <<NN>>
provide --> method : obj
component [shop] as shop <<NN>>
component [pet] as pet <<NN>>
shop --> pet : compound
component [offer] as offer <<VB>>
component [shop] as shop <<NN>>
offer --> shop : nsubj
component [sentence] as sentence <<NN>>
component [offer] as offer <<VB>>
sentence --> offer : dep
component [offer] as offer <<VB>>
component [range] as range <<NN>>
offer --> range : obj
component [product] as product <<NNS>>
component [pet] as pet <<NN>>
product --> pet : compound
component [range] as range <<NN>>
component [product] as product <<NNS>>
range --> product : nmod:of
component [product] as product <<NNS>>
component [food] as food <<NN>>
product --> food : nmod:including
component [product] as product <<NNS>>
component [toy] as toy <<NNS>>
product --> toy : nmod:including
component [food] as food <<NN>>
component [toy] as toy <<NNS>>
food --> toy : conj:and
component [product] as product <<NNS>>
component [accessory] as accessory <<NNS>>
product --> accessory : nmod:including
component [food] as food <<NN>>
component [accessory] as accessory <<NNS>>
food --> accessory : conj:and
component [product] as product <<NNS>>
component [groom] as groom <<VBG>>
product --> groom : nmod:including
component [food] as food <<NN>>
component [groom] as groom <<VBG>>
food --> groom : conj:and
component [groom] as groom <<VBG>>
component [supply] as supply <<NNS>>
groom --> supply : obj
component [action] as action <<NNP>>
component [notify] as notify <<VBZ>>
action --> notify : parataxis
component [notify] as notify <<VBZ>>
component [customer] as customer <<NN>>
notify --> customer : obj
component [suggest] as suggest <<VBZ>>
component [item] as item <<NN>>
suggest --> item : nsubj
component [notify] as notify <<VBZ>>
component [suggest] as suggest <<VBZ>>
notify --> suggest : ccomp
component [suggest] as suggest <<VBZ>>
component [offer] as offer <<NNS>>
suggest --> offer : obj
component [notify] as notify <<VB>>
component [offer] as offer <<NNS>>
notify --> offer : nsubj:xsubj
component [suggest] as suggest <<VBZ>>
component [notify] as notify <<VB>>
suggest --> notify : xcomp
component [payment] as payment <<NN>>
component [decline] as decline <<VBN>>
payment --> decline : acl
component [decline] as decline <<VBN>>
component [payment] as payment <<NN>>
decline --> payment : nsubj:pass
component [payment] as payment <<NN>>
component [decline] as decline <<VBN>>
payment --> decline : dep
component [decline] as decline <<VBN>>
component [fund] as fund <<NNS>>
decline --> fund : dep
component [create] as create <<VBN>>
component [uc] as uc <<NNP>>
create --> uc : nsubj
component [create] as create <<VBN>>
component [petshop_usecases] as petshop_usecases <<NNS>>
create --> petshop_usecases : obl:from
component [product] as product <<NN>>
component [requirement] as requirement <<NNS>>
product --> requirement : compound
component [stock] as stock <<NN>>
component [product] as product <<NN>>
stock --> product : nsubj
component [supply] as supply <<NNS>>
component [food] as food <<NN>>
supply --> food : compound
component [payment] as payment <<NN>>
component [process] as process <<NNS>>
payment --> process : compound
component [payment] as payment <<NN>>
component [confirm] as confirm <<VBZ>>
payment --> confirm : conj:and
component [confirm] as confirm <<VBZ>>
component [transaction] as transaction <<NN>>
confirm --> transaction : obj
component [cancel] as cancel <<VBN>>
component [transaction] as transaction <<NN>>
cancel --> transaction : nsubj:pass
component [process] as process <<VBN>>
component [payment] as payment <<NN>>
process --> payment : nsubj:pass
component [cancel] as cancel <<VBN>>
component [process] as process <<VBN>>
cancel --> process : ccomp
component [remain] as remain <<VBZ>>
component [inventory] as inventory <<NN>>
remain --> inventory : nsubj
component [cancel] as cancel <<VBN>>
component [remain] as remain <<VBZ>>
cancel --> remain : ccomp
component [inform] as inform <<VBN>>
component [customer] as customer <<NN>>
inform --> customer : nsubj:pass
component [cancel] as cancel <<VBN>>
component [inform] as inform <<VBN>>
cancel --> inform : conj:and
component [decline] as decline <<VBD>>
component [payment] as payment <<NN>>
decline --> payment : nsubj
component [item] as item <<NN>>
component [decline] as decline <<VBD>>
item --> decline : dep
component [select] as select <<VBZ>>
component [customer] as customer <<NN>>
select --> customer : nsubj
component [add] as add <<VBZ>>
component [customer] as customer <<NN>>
add --> customer : nsubj
component [select] as select <<VBZ>>
component [product] as product <<NNS>>
select --> product : obj
component [select] as select <<VBZ>>
component [add] as add <<VBZ>>
select --> add : conj:and
component [add] as add <<VBZ>>
component [cart] as cart <<NN>>
add --> cart : obl:to
component [availability] as availability <<NN>>
component [product] as product <<NN>>
availability --> product : compound
component [validate] as validate <<VBZ>>
component [availability] as availability <<NN>>
validate --> availability : obj
component [validate] as validate <<VBZ>>
component [calculate] as calculate <<VBZ>>
validate --> calculate : conj:and
component [calculate] as calculate <<VBZ>>
component [cost] as cost <<NN>>
calculate --> cost : obj
component [present] as present <<JJ>>
component [customer] as customer <<NN>>
present --> customer : nsubj
component [log] as log <<VBD>>
component [customer] as customer <<NN>>
log --> customer : nsubj
component [present] as present <<JJ>>
component [store] as store <<NN>>
present --> store : obl:at
component [present] as present <<JJ>>
component [log] as log <<VBD>>
present --> log : conj:or
component [shop] as shop <<NN>>
component [online] as online <<JJ>>
shop --> online : amod
component [log] as log <<VBD>>
component [shop] as shop <<NN>>
log --> shop : obl:into
component [transaction] as transaction <<NNS>>
component [payment] as payment <<NN>>
transaction --> payment : compound
component [quantity] as quantity <<NNS>>
component [update] as update <<NNS>>
quantity --> update : compound
component [quantity] as quantity <<NNS>>
component [inventory] as inventory <<NN>>
quantity --> inventory : compound
component [browse] as browse <<VBZ>>
component [customer] as customer <<NN>>
browse --> customer : nsubj
component [category] as category <<NNS>>
component [available] as available <<JJ>>
category --> available : amod
component [product] as product <<NN>>
component [pet] as pet <<NN>>
product --> pet : compound
component [category] as category <<NNS>>
component [product] as product <<NN>>
category --> product : compound
component [browse] as browse <<VBZ>>
component [category] as category <<NNS>>
browse --> category : iobj
component [category] as category <<NNS>>
component [food] as food <<NN>>
category --> food : dep
component [food] as food <<NN>>
component [toy] as toy <<NNS>>
food --> toy : conj
component [food] as food <<NN>>
component [accessory] as accessory <<NNS>>
food --> accessory : conj
component [food] as food <<NN>>
component [groom] as groom <<VBG>>
food --> groom : acl
component [groom] as groom <<VBG>>
component [supply] as supply <<NNS>>
groom --> supply : obj
component [product] as product <<NN>>
component [stock] as stock <<NN>>
product --> stock : nmod:out_of
component [product] as product <<NN>>
component [select] as select <<VBN>>
product --> select : amod
component [stock] as stock <<NN>>
component [product] as product <<NN>>
stock --> product : nsubj
component [arrive] as arrive <<VBZ>>
component [customer] as customer <<NN>>
arrive --> customer : nsubj
component [shop] as shop <<NN>>
component [pet] as pet <<NN>>
shop --> pet : compound
component [arrive] as arrive <<VBZ>>
component [shop] as shop <<NN>>
arrive --> shop : obl:at
component [store] as store <<NN>>
component [online] as online <<JJ>>
store --> online : amod
component [shop] as shop <<NN>>
component [store] as store <<NN>>
shop --> store : appos
component [arrive] as arrive <<VBZ>>
component [intent] as intent <<NN>>
arrive --> intent : obl:with
component [intent] as intent <<NN>>
component [purchase] as purchase <<VB>>
intent --> purchase : acl:to
component [product] as product <<NNS>>
component [pet] as pet <<NN>>
product --> pet : compound
component [purchase] as purchase <<VB>>
component [product] as product <<NNS>>
purchase --> product : obj
component [assistant] as assistant <<NN>>
component [shop] as shop <<VB>>
assistant --> shop : amod
component [request] as request <<VBN>>
component [assistant] as assistant <<NN>>
request --> assistant : nsubj
component [present] as present <<VBZ>>
component [assistant] as assistant <<NN>>
present --> assistant : nsubj
component [process] as process <<VBZ>>
component [assistant] as assistant <<NN>>
process --> assistant : nsubj
component [action] as action <<NNP>>
component [request] as request <<VBN>>
action --> request : parataxis
component [request] as request <<VBN>>
component [item] as item <<NNS>>
request --> item : obj
component [item] as item <<NNS>>
component [stock] as stock <<NN>>
item --> stock : nmod:from
component [action] as action <<NNP>>
component [present] as present <<VBZ>>
action --> present : parataxis
component [request] as request <<VBN>>
component [present] as present <<VBZ>>
request --> present : conj:and
component [present] as present <<VBZ>>
component [option] as option <<NNS>>
present --> option : obj
component [action] as action <<NNP>>
component [process] as process <<VBZ>>
action --> process : parataxis
component [request] as request <<VBN>>
component [process] as process <<VBZ>>
request --> process : conj:and
component [process] as process <<VBZ>>
component [sale] as sale <<NN>>
process --> sale : obj
component [process] as process <<VBZ>>
component [register] as register <<NN>>
process --> register : obl:at
component [purchase] as purchase <<NN>>
component [store] as store <<NN>>
purchase --> store : compound
component [purchase] as purchase <<NN>>
component [assistance] as assistance <<NN>>
purchase --> assistance : nmod:with
component [ask] as ask <<VBZ>>
component [customer] as customer <<NN>>
ask --> customer : nsubj
component [assistant] as assistant <<NN>>
component [shop] as shop <<NN>>
assistant --> shop : compound
component [ask] as ask <<VBZ>>
component [assistant] as assistant <<NN>>
ask --> assistant : obj
component [assistant] as assistant <<NN>>
component [help] as help <<NN>>
assistant --> help : nmod:for
component [assistant] as assistant <<NN>>
component [browsing] as browsing <<NN>>
assistant --> browsing : nmod:instead_of
component [sell] as sell <<VBG>>
component [elaborate] as elaborate <<VBD>>
sell --> elaborate : dep
component [elaborate] as elaborate <<VBD>>
component [sentence] as sentence <<NN>>
elaborate --> sentence : obl:from
component [sentence] as sentence <<NN>>
component [petshop_usecases] as petshop_usecases <<NNPS>>
sentence --> petshop_usecases : nmod:of
component [update] as update <<NNS>>
component [inventory] as inventory <<NN>>
update --> inventory : compound
component [reflect] as reflect <<VBN>>
component [update] as update <<NNS>>
reflect --> update : nsubj:pass
component [reflect] as reflect <<VBN>>
component [time] as time <<NN>>
reflect --> time : obl:in
component [reflect] as reflect <<VBN>>
component [channel] as channel <<NNS>>
reflect --> channel : obl:across
component [store] as store <<NN>>
component [pos] as pos <<NN>>
store --> pos : dep
component [store] as store <<NN>>
component [online] as online <<NN>>
store --> online : dep
component [pos] as pos <<NN>>
component [online] as online <<NN>>
pos --> online : conj:and
component [proceed] as proceed <<VBZ>>
component [customer] as customer <<NN>>
proceed --> customer : nsubj
component [payment] as payment <<NN>>
component [checkout] as checkout <<NN>>
payment --> checkout : compound
component [proceed] as proceed <<VBZ>>
component [payment] as payment <<NN>>
proceed --> payment : obl:to
component [restrict] as restrict <<VBN>>
component [age] as age <<NN>>
restrict --> age : obl
component [item] as item <<NNS>>
component [restrict] as restrict <<VBN>>
item --> restrict : amod
component [require] as require <<VBP>>
component [item] as item <<NNS>>
require --> item : nsubj
component [item] as item <<NNS>>
component [medication] as medication <<NNS>>
item --> medication : appos
component [purchase] as purchase <<VBN>>
component [customer] as customer <<NN>>
purchase --> customer : nsubj
component [purchase] as purchase <<VBN>>
component [have] as have <<VBZ>>
purchase --> have : aux
component [product] as product <<NNS>>
component [pet] as pet <<NN>>
product --> pet : compound
component [purchase] as purchase <<VBN>>
component [product] as product <<NNS>>
purchase --> product : obj
component [process] as process <<VBN>>
component [payment] as payment <<NN>>
process --> payment : nsubj:pass
component [process] as process <<VBN>>
component [have] as have <<VBZ>>
process --> have : aux
component [purchase] as purchase <<VBN>>
component [process] as process <<VBN>>
purchase --> process : parataxis
component [quantity] as quantity <<NNS>>
component [inventory] as inventory <<NN>>
quantity --> inventory : compound
component [update] as update <<VBN>>
component [quantity] as quantity <<NNS>>
update --> quantity : nsubj:pass
component [process] as process <<VBN>>
component [update] as update <<VBN>>
process --> update : ccomp
component [provide] as provide <<VBN>>
component [receipt] as receipt <<NN>>
provide --> receipt : nsubj:pass
component [purchase] as purchase <<VBN>>
component [provide] as provide <<VBN>>
purchase --> provide : parataxis
component [process] as process <<VBN>>
component [provide] as provide <<VBN>>
process --> provide : conj:and
@enduml