@startuml
title Apache Causeway - Qualities of the Framework
!include <tupadr3/font-awesome/envira>
!include <tupadr3/font-awesome/envira>
!include <tupadr3/font-awesome/cog>
!include <tupadr3/font-awesome/dollar>
!include <tupadr3/font-awesome/user>

'// developer perspective
[<img:https://cwiki.apache.org/confluence/download/thumbnails/240882061/causeway-logo-65x48.png{scale=0.5}>\nApache\nCauseway] as fw #white
file "<$user{scale=0.5}>Comprehensibility" as c #white
file "<$user{scale=0.5}>\nDeveloper\nHappiness" as dh #white

'// description
(Design\nPatterns) as p #lightblue
(<b>Domain\n<b>Driven\n<b>Design) as ddd #lightblue
(Test\nAutomation) as ta #lightblue
fw --> ddd : enforces\nuse of
ddd --> p : is a\ncollection of
p --> c : use of DP.\nis\nBestPractice

'// artefacts
together {
    (<$cog{scale=0.5}>\nGenerated\nUI) as uig #lightgreen
    (<$cog{scale=0.5}>\nGenerated\nDB) as dbg #lightgreen
    (<$cog{scale=0.5}>\nGenerated\nRESTful\nAPI) as ro #lightgreen
}
(Sustainable\nCode) as sc #lightgreen
fw -> uig : offers
fw -> dbg : offers
fw -> ro : offers
uig --> ta : promotes
ta --> sc
c --> sc

note bottom of uig #gold
[[https://en.wikipedia.org/wiki/Unique_selling_proposition Unique\nSelling\nProposition]]
end note

'// role
(<B>Lean Code</B>\nDevelopment\nPlatform) as lc #gold
'URL="https://en.wikipedia.org/wiki/Low-code_development_platforms" style=filled fillcolor=yellow]

lc ---> c
fw --> lc : is a

'// economic factors
(Time\nTo\nMarket) as ttm #pink
(Productivity) as pdc #pink
(Human\nResources) as hr #pink
(<$dollar{scale=0.5}>\nEconomic\nSuccess) as es #pink
pdc --> dh : increases
sc --> pdc
dbg --> ttm : shortens
uig --> ttm : shortens
dh -> hr : increases\nsupply of
hr -> es
ttm -> es
pdc -> es

'// notes
file "Allows for tight \n<B>feedback loop </B>,\n ideal for \n<B>agile</B> projects" as uig_note #lightyellow
uig_note .. uig
uig_note .. dbg

note right of ro
Allows for
* custom UI
* automation
** testing
** scheduling
end note

note right of ttm
Key
factor for
<B>innovative,
<b>agile
projects
end note

ddd ..> uig : suggests \nto avoid \n <B>Smart UI </B>,\n Anti Pattern

legend
  [[https://en.wikipedia.org/wiki/Object_Modeling_in_Color Modeling in Color]]
  * <back:pink>pink: moment-interval (here: economic aspects)
    Does it represent a moment or interval of time that we need to remember and work with for legal or business reasons?
    Examples in business systems generally model activities involving people, places and things such as a sale, an order,
    a rental, an employment, making a journey, etc.
  * <back:lightyellow>yellow: roles
    Is it a way of participating in an activity (by either a person, place, or thing)?
    A person playing the role of<an employee in an employment, a thing playing the role of a product in a sale,
    a location playing the role of a classroom for a training course, are examples of roles.
  *<back:lightblue>blue: description (here: documentation))
    Is it simply a catalog-entry-like description which classifies or 'labels' an object?
    For example, the make and model of a car categorises or describes a number of physical vehicles.
    The relationship between the blue description and green party, place or thing is a type-instance relationship
    based on differences in the values of data items held in the 'type' object.
  *<back:lightgreen>green: party, place, or thing (here: artifacts)
    Something tangible, uniquely identifiable. Typically the role-players in a system.
    People are green. Organizations are green. The physical objects involved in a rental such as the physical DVDs are green.
    Normally, if you get through the above three questions and end up here, your class is a "green." +
end legend

@enduml
