services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
#      - nlp
#     - kroki
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  nlp:
    build:
      context: docker/corenlp/
      dockerfile: Dockerfile
    image: corenlp:latest
    ports:
      - "8999:9000"
    environment:
      - JVM_OPTS=-Xmx4g

  db:
    image: postgres:10.23-alpine
    container_name: domox-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"

#  kroki:
#    image: yuzutech/kroki
#    ports:
#      - "8000:8000"
