services:
  stanford-corenlp-server:
    build:
      context: docker/stanford-corenlp-server/
      dockerfile: Dockerfile
    image: stanford-corenlp-server:latest
    ports:
      - "8999:9000"
    environment:
      - JVM_OPTS=-Xmx4g

  db:
    image: postgres:10.23-alpine
    container_name: domox-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"

#  kroki:
#    image: yuzutech/kroki
#    ports:
#      - "8000:8000"

#  marytts:
#    image: synesthesiam/marytts:5.2
#    ports:
#      - "59125:59125"

#  nlpbox:
#    image: nlpbox/corenlp
#    ports:
#      - "8999:9000"
#    environment:
#      - JVM_OPTS=-Xmx4g

