version: "3"
services:
  nlp:
    image: nlpbox/corenlp
    ports:
      - "8090:9000"
    environment:
      - JVM_OPTS=-Xmx4g

#  kroki:
#    image: yuzutech/kroki
#    ports:
#      - "8000:8000"

#  nlp:
#    image: johnsnowlabs/nlp-server:latest
#    ports:
#      - "5000:5000"

  db:
    image: postgres:10.23-alpine
#    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"

#  marytts:
#    image: synesthesiam/marytts:5.2
#    ports:
#      - "59125:59125"
