classDiagram = [classDeclaration {classDeclaration}]
classDeclaration = "class", className, [classModifiers], [classBody]
classModifiers = ["abstract" | "interface"]
classBody = "{", [classAttributes], [classMethods], "}"
classAttributes = attributeDeclaration {attributeDeclaration}
attributeDeclaration = attributeName, ":", attributeType
classMethods = methodDeclaration {methodDeclaration}
methodDeclaration = methodName, "(", [methodParameters], ")", ":", returnType
methodParameters = parameterDeclaration {",", parameterDeclaration}
parameterDeclaration = parameterName, ":", parameterType
className = identifier
attributeName = identifier
attributeType = identifier
methodName = identifier
returnType = identifier
parameterName = identifier
parameterType = identifier
identifier = letter {letter | digit | "_"}
letter = "A" | "B" | ... | "Z" | "a" | "b" | ... | "z"
digit = "0" | "1" | ... | "9"