@startdot
digraph s1 {
  graph [nodesep=0.1, ranksep=2, splines=true]
  node [shape=plaintext]
  {
      rank=same
      s1 [ordering=out label=""]
      edge [style=invis]

      s1->W10
      s1->W9
      s1->W8
      s1->W7
      s1->W6
      s1->W5
      s1->W4
      s1->W3
      s1->W2
      s1->W1
      edge [style=""]
      W1 [label=<
        <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0">
          <TR><TD BGCOLOR="lavender">PRP</TD></TR>
          <TR><TD BORDER="0">We</TD></TR>
       </TABLE>>]
      W2 [shape=plaintext  label=<
       <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0">
          <TR><TD BGCOLOR="green1">PRP</TD></TR>
          <TR ><TD BORDER="0">are</TD></TR>
       </TABLE>>]
      W3 [shape=plaintext  label=<
       <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0">
          <TR><TD BGCOLOR="green1">PRP</TD></TR>
          <TR ><TD BORDER="0">facing</TD></TR>
       </TABLE>>]
      W4 [shape=plaintext  label=<
       <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0">
          <TR><TD BGCOLOR="lavender">PRP</TD></TR>
          <TR><TD BORDER="0">a</TD></TR>
       </TABLE>>]

      W5 [shape=plaintext  label=<
       <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0">
          <TR><TD BGCOLOR="lavender">PRP</TD></TR>
          <TR><TD BORDER="0">failure</TD></TR>
       </TABLE>>]
      W6 [shape=plaintext  label=<
       <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0">
          <TR><TD BGCOLOR="lavender">PRP</TD></TR>
          <TR><TD BORDER="0">when</TD></TR>
       </TABLE>>]
      W7 [shape=plaintext  label=<
       <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0">
          <TR><TD BGCOLOR="lavender">PRP</TD></TR>
          <TR><TD BORDER="0">running</TD></TR>
       </TABLE>>]
      W8 [shape=plaintext  label=<
       <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0">
          <TR><TD BGCOLOR="lavender">VBG</TD></TR>
          <TR><TD BORDER="0">xyz</TD></TR>
       </TABLE>>]
      W9 [shape=plaintext  label=<
       <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0">
          <TR><TD BGCOLOR="lavender">NN</TD></TR>
          <TR><TD BORDER="0">job</TD></TR>
       </TABLE>>]
      W10 [shape=plaintext  label=<
       <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0">
          <TR><TD BGCOLOR="lavender">.</TD></TR>
          <TR><TD BORDER="0">.</TD></TR>
       </TABLE>>]

       edge[constraint=false]
       W3 -> W2 [label="\naux"]
       W3:n -> W1 [label="\nblah 1"]
       W3:ne-> W5:nw [label="\nblah 2"]
       W3:s -> W7:s [label="\nblah 3"]
       W3:ne -> W10:nw [label="\nblah 4"]

    }
}
@enddot

https://stackoverflow.com/questions/52743748/pretty-display-of-a-sentence-and-its-grammatical-dependencies

   A [label="Node A"];
       B [label="Node B"];
       C [label="Node C"];
       D [label="Node D"];

       A:n -> B:s [label="North to South"];
       A:ne -> C:sw [label="Northeast to Southwest"];
       A:e -> D:w [label="East to West"];
