@startuml
skinparam ranksep 1
skinparam nodesep 5
skinparam linetype polyline

card We as W1 #line:transparent
card PRP as N1 #lightblue
N1 -d-( W1

card are as W2 #line:transparent
card VB as N2 #lightblue
N2 -d-( W2

card facing as W3 #line:transparent
card VBG as N3 #lightblue
N3 -d-( W3

card a as W4 #line:transparent
card PRP as N4 #lightblue
N4 -d-( W4

card failure as W5 #line:transparent
card NN as N5 #lightblue
N5 -d-( W5

card when as W6 #line:transparent
card PRP as N6 #lightblue
N6 -d-( W6

card running as W7 #line:transparent
card VBG as N7 #lightblue
N7 -d-( W7

card XYZ as W8 #line:transparent
card VBG as N8 #lightblue
N8 -d-( W8

card job as W9 #line:transparent
card NN as N9 #lightblue
N9 -d-( W9

card . as W10 #line:transparent
card PUNCT as N10 #lightblue
N10 -d-( W10

N1 -r-> N2 #transparent
N2 -r-> N3 #transparent
N3 -r-> N4 #transparent
N4 -r-> N5 #transparent
N5 -r-> N6 #transparent
N6 -r-> N7 #transparent
N7 -r-> N8 #transparent
N8 -r-> N9 #transparent
N9 -r-> N10 #transparent
'Handling directional edges with PlantUML syntax
card "blah1" as N3N1 #white
'N3 -l-> N1 : "blah 1"
N3 -u- N3N1
N3N1 -d-> N1

N3 -r-> N7 : "blah 3"
N3 -r-> N5 : "blah 2"
N3 -r-> N10 : "blah 4"
N3 -l-> N2 : "aux"

@enduml
