@startuml
'left to right direction

' Define the nodes in the same rank
rectangle {
rectangle "We\nPRP" as w1 #lavender
rectangle "are\nPRP" as w2 #green
rectangle "facing\nPRP" as w3 #green
rectangle "a\nPRP" as w4 #lavender
rectangle "failure\nPRP" as w5 #lavender
rectangle "when\nPRP" as w6 #lavender
rectangle "running\nPRP" as w7 #lavender
rectangle "xyz\nVBG" as w8 #lavender
rectangle "job\nNN" as w9 #lavender
rectangle ".\nPUNCT" as w10 #lavender
}
' Invisible edges to maintain layout
w1 . w2 #white
w2 . w3 #white
w3 . w4 #white
w4 . w5 #white
w5 . w6 #white
w6 . w7 #white
w7 . w8 #white
w8 . w9 #white
w9 . w10 #white

' Define visible edges with labels
w3 ------> w2 : aux
w3 ------> w1 : blah 1
w3 ------> w5 : blah 2
w3 ------> w7 : blah 3
w3 ------> w10 : blah 4
@enduml