@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "domox.Analysis#init()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": ""
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false // root node is included
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "domox.Analysis"
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_95767211 { 
   	label=domox
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1757613791 { 
   	label=Analysis
	labeljust=l
	fillcolor=white
	style=filled
   
   Analysis95767211XXXinit0[
	label="+ init()"
	style=filled
	fillcolor=white
	tooltip="Analysis

null"
	penwidth=4
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_99650 { 
   	label=dom
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1836037986 { 
   	label=rqm
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1801330039 { 
   	label=Documents
	labeljust=l
	fillcolor=white
	style=filled
   
   Documents1785149215XXXlistAll0[
	label="+ listAll()"
	style=filled
	fillcolor=white
	tooltip="Documents

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
Analysis95767211XXXinit0 -> Documents1785149215XXXlistAll0;
    
}
@enduml