@startmindmap
caption: Though a new paradigm may possess few or none none of the capabilities of its predecessor , it nevertheless preserves a large part of the concrete problem-solving activity activity that science has gained through its predecessors .
*[#E74C3C]:<U+0023>19
<b>preserves</b>
VBZ / <i>ROOT</i>;
**[#AAB7B8]:<U+0023>6
<b>possess</b>
VB / <i>advcl:though</i>;
***[#F39C12]:<U+0023>1
<b>Though</b>
IN / <i>mark</i>;
***[#3498DB]:<U+0023>4
<b>paradigm</b>
NN / <i>nsubj</i>;
****[#F39C12]:<U+0023>2
<b>a</b>
DT / <i>det</i>;
****[#2ECC71]:<U+0023>3
<b>new</b>
JJ / <i>amod</i>;
***[#F39C12]:<U+0023>5
<b>may</b>
MD / <i>aux</i>;
***[#3498DB]:<U+0023>7
<b>few</b>
JJ / <i>dobj</i>;
****[#F39C12]:<U+0023>8
<b>or</b>
CC / <i>cc</i>;
****[#AAB7B8]:<U+0023>9
<b>none</b>
NN / <i>conj:or</i>;
****[#AAB7B8]:<U+0023>12
<b>capabilities</b>
NNS / <i>nmod:of</i>;
*****[#F39C12]:<U+0023>10
<b>of</b>
IN / <i>case</i>;
*****[#F39C12]:<U+0023>11
<b>the</b>
DT / <i>det</i>;
*****[#AAB7B8]:<U+0023>15
<b>predecessor</b>
NN / <i>nmod:of</i>;
******[#F39C12]:<U+0023>13
<b>of</b>
IN / <i>case</i>;
******[#AAB7B8]:<U+0023>14
<b>its</b>
PRP$ / <i>nmod:poss</i>;
***[#3498DB]:<U+0023>9
<b>none</b>
NN / <i>dobj</i>;
**[#BDC3C7]:<U+0023>16
<b>,</b>
, / <i>punct</i>;
**[#3498DB]:<U+0023>17
<b>it</b>
PRP / <i>nsubj</i>;
**[#2ECC71]:<U+0023>18
<b>nevertheless</b>
RB / <i>advmod</i>;
**[#3498DB]:<U+0023>22
<b>part</b>
NN / <i>dobj</i>;
***[#F39C12]:<U+0023>20
<b>a</b>
DT / <i>det</i>;
***[#2ECC71]:<U+0023>21
<b>large</b>
JJ / <i>amod</i>;
***[#AAB7B8]:<U+0023>27
<b>activity</b>
NN / <i>nmod:of</i>;
****[#F39C12]:<U+0023>23
<b>of</b>
IN / <i>case</i>;
****[#F39C12]:<U+0023>24
<b>the</b>
DT / <i>det</i>;
****[#2ECC71]:<U+0023>25
<b>concrete</b>
JJ / <i>amod</i>;
****[#2ECC71]:<U+0023>26
<b>problem-solving</b>
JJ / <i>amod</i>;
****[#AAB7B8]:<U+0023>28
<b>that</b>
WDT / <i>ref</i>;
****[#AAB7B8]:<U+0023>31
<b>gained</b>
VBN / <i>acl:relcl</i>;
*****[#3498DB]:<U+0023>27
<b>activity</b>
NN / <i>dobj</i>;
*****[#3498DB]:<U+0023>29
<b>science</b>
NN / <i>nsubj</i>;
*****[#F39C12]:<U+0023>30
<b>has</b>
VBZ / <i>aux</i>;
*****[#AAB7B8]:<U+0023>34
<b>predecessors</b>
NNS / <i>nmod:through</i>;
******[#F39C12]:<U+0023>32
<b>through</b>
IN / <i>case</i>;
******[#AAB7B8]:<U+0023>33
<b>its</b>
PRP$ / <i>nmod:poss</i>;
**[#BDC3C7]:<U+0023>35
<b>.</b>
. / <i>punct</i>;
@endmindmap