package domox.dom.nlp;

import lombok.Getter;

public enum TdType {
    ROOT("ROOT"),
    ACL("acl"),
    ACL_IN("acl:in"),
    ACL_TO("acl:to"),
    ACL_RELCL("acl:relcl"),
    ADVCL("advcl"),
    ADVCL_AS("advcl:as"),
    ADVCL_BEFORE("advcl:before"),
    ADVCL_BASED_ON("advcl:based_on"),
    ADVCL_IF("advcl:if"),
    ADVCL_IN("advcl:in"),
    ADVCL_ON("advcl:on"),
    ADVCL_SO("advcl:so"),
    ADVCL_TO("advcl:to"),
    ADVCL_UNTIL("advcl:until"),
    ADVCL_WHILE("advcl:while"),
    ADVCL_WITHOUT("advcl:without"),
    ADVMOD("advmod"),
    AMOD("amod"),
    APPOS("appos"),
    AUX("aux"),
    AUX_PASS("aux:pass"),
    CASE("case"),
    CC("cc"),
    CC_PRECONJ("cc:preconj"),
    CCOMP("ccomp"),
    CLF("clf"),
    COMPOUND("compound"),
    COMPOUND_PRT("compound:prt"),
    CONJ("conj"),
    CONJ_AND("conj:and"),
    CONJ_AMP_AND("conj:&"),
    CONJ_NEGCC("conj:negcc"),
    CONJ_OR("conj:or"),
    COP("cop"),
    CSUBJ("csubj"),
    CSUBJ_PASS("csubj:pass"),
    DEP("dep"),
    DET("det"),
    DET_QMOD("det:qmod"),
    DISCOURSE("discourse"),
    DISLOCATED("dislocated"),
    EXPL("expl"),
    FIXED("fixed"),
    FLAT("flat"),
    FLAT_NAME("flat:name"),
    GOESWITH("goeswith"),
    IOBJ("iobj"),
    LIST("list"),
    MARK("mark"),
    NMOD("nmod"),
    NMOD_AT("nmod:at"),
    NMOD_ACROSS("nmod:across"),
    NMOD_AFTER("nmod:after"),
    NMOD_ALONGSIDE("nmod:alongside"),
    NMOD_BEFORE("nmod:before"),
    NMOD_BETWEEN("nmod:between"),
    NMOD_BY("nmod:by"),
    NMOD_DURING("nmod:during"),
    NMOD_FROM("nmod:from"),
    NMOD_FOR("nmod:for"),
    NMOD_IN("nmod:in"),
    NMOD_INCLUDING("nmod:including"),
    NMOD_INSTEAD_OF("nmod:instead_of"),
    NMOD_OF("nmod:of"),
    NMOD_ON("nmod:on"),
    NMOD_OUT_OF("nmod:out_of"),
    NMOD_PAST("nmod:past"),
    NMOD_PER("nmod:per"),
    NMOD_POSS("nmod:poss"),
    NMOD_ON_TOP_OF("nmod:on_top_of"),
    NMOD_SUCH_AS("nmod:such_as"),
    NMOD_TO("nmod:to"),
    NMOD_WITH("nmod:with"),
    NMOD_WITHOUT("nmod:without"),
    NSUBJ("nsubj"),
    NSUBJ_PASS("nsubj:pass"),
    NSUBJPASS("nsubjpass"), //TODO
    NSUBJ_XSUBJ("nsubj:xsubj"),
    NUMMOD("nummod"),
    OBJ("obj"),
    OBL("obl"),
    OBL_ABOUT("obl:about"),
    OBL_ACCORDING_TO("obl:according_to"),
    OBL_ACROSS("obl:across"),
    OBL_AFTER("obl:after"),
    OBL_AGENT("obl:agent"),
    OBL_AS("obl:as"),
    OBL_AT("obl:at"),
    OBL_BEFORE("obl:before"),
    OBL_BY("obl:by"),
    OBL_CONCERNING("obl:concerning"),
    OBL_DURING("obl:during"),
    OBL_FOR("obl:for"),
    OBL_FROM("obl:from"),
    OBL_IN("obl:in"),
    OBL_INSTEAD_OF("obl:instead_of"),
    OBL_INTO("obl:into"),
    OBL_NPMOD("obl:npmod"),
    OBL_OF("obl:of"),
    OBL_ON("obl:on"),
    OBL_OUT_OF("obl:out_of"),
    OBL_OVER("obl:over"),
    OBL_PER("obl:per"),
    OBL_THROUGH("obl:through"),
    OBL_THROUGHOUT("obl:throughout"),
    OBL_TMOD("obl:tmod"),
    OBL_TO("obl:to"),
    OBL_UNDER("obl:under"),
    OBL_UNTIL("obl:until"),
    OBL_VIA("obl:via"),
    OBL_WITH("obl:with"),
    OBL_WITHIN("obl:within"),
    OBL_WITHOUT("obl:without"),
    ORPHAN("orphan"),
    PARATAXIS("parataxis"),
    PUNCT("punct"),
    REF("ref"),
    REPARANDUM("reparandum"),
    VOCATIVE("vocative"),
    XCOMP("xcomp");

    @Getter
    final String code;

    TdType(String code) {
        this.code = code;
    }

    public static TdType fromCode(String code) {
        for (TdType type : TdType.values()) {
            if (type.getCode().equals(code)) {
                return type;
            }
        }
        throw new IllegalArgumentException("No enum constant found for code: " + code);
    }

}
